behaviors:
  NPCNavigation:
    trainer_type: dqn
    hyperparameters:
      buffer_size: 100000
      batch_size: 64
      learning_rate: 3e-4
    network_settings:
      hidden_units: 128
      num_layers: 2
    max_steps: 10000
    summary_freq: 1000
